### ISSUE TITLE
Docs not available

### ISSUE THREAD

**Issue by hexin** [pizzaql/pizzaql#10]
The page [docs page](https://nicedoc.io/pizzaql/docs) returns the 404 page 
<img width="1345" alt="Screenshot 2019-05-04 at 19 02 29" src="https://user-images.githubusercontent.com/1080437/57182460-99298000-6e9f-11e9-8e78-49a9661b4c05.png">

**Comment by jackwilsdon** [comment]
Looks like the URL should be https://nicedoc.io/pizzaql/pizzaql instead of https://nicedoc.io/pizzaql/docs, but all that seems to show is the README.md, and doesn't fully align with https://pizzaql.now.sh which also had usage instructions.

**Comment by xxczaki** [comment]
@hexin @jackwilsdon Sorry for the delay. The current docs page should be available at  https://nicedoc.io/pizzaql/docs. It is basically the README.md of https://github.com/pizzaql/docs, but served using [Nicedoc](nicedoc.io). 

However, this is a temporary setup :smile: I'm currently making a new documentation, which will be available at pizzaql.now.sh. 

Stay tuned ;)
