### ISSUE TITLE
Update to Stripe 3

### ISSUE THREAD

**Issue by xxczaki** [pizzaql/pizzaql#14]
Currently, to handle the payment we are using the [react-stripe-checkout](https://www.npmjs.com/package/react-stripe-checkout) package. 

Unfortunately it looks like it is no longer maintained and because Stripe is going to deprecate the old checkout in September this year. 

Because of that, we need to migrate to Stripe Elements.

**Comment by shonore** [comment]
I might be able to assist

**Comment by xxczaki** [comment]
@shonore That's great! Here is the code, that currently handles Stripe payment: https://github.com/pizzaql/pizzaql/blob/337b84d1d8e5301bb91631f04e7257c0ddc65799/frontend/components/form/order-placement-form.js#L164-L173

**Comment by xxczaki** [comment]
Closing this, as the rewritten version of PizzaQL is WIP - https://github.com/pizzaql/next
