### ISSUE TITLE
Token Refreshing?

### ISSUE THREAD

**Issue by CaptainChemist** [pizzaql/pizzaql#4]
I really love this example app, thank you! It would be great if you could provide a solution for token refreshing. Auth0 will expire the tokens after 2 hours and the renewSession in Auth0 doesn't seem to be compatible with server-side code. How did you get around this? Is there a way to just disable token refreshing if it isn't really necessary?

**Comment by xxczaki** [comment]
Hi, for integrating the Auth0 with Next.js I used [this tutorial](https://blog.fullstacktraining.com/using-next-js-and-auth0/) :smile:

**Comment by xxczaki** [comment]
Also note, that you can adjust the JWT expiration time in you Auth0 dashboard.

**Comment by CaptainChemist** [comment]
Thanks, I saw this too! It works great but it, unfortunately, doesn't have the token refreshing aspect of it. I wish you could just delete the expiration time entirely in the auth0 dashboard. I don't have a working version yet, but I think we might be able to refresh the token using the `onError` link function. 

```
    onError(({ graphQLErrors, networkError, operation, forward }) => {
      if (graphQLErrors) {
        const unauthorizedErrors = _.filter(graphQLErrors, ["message", "Context creation failed: Unauthorized"]).length;

        if (unauthorizedErrors > 0) {
          console.log(graphQLErrors);
          return new Observable(async observer => {
            try {
              await silentAuth();
              const token = getToken();
              const Authorization = token ? `Bearer ${token}` : "Bearer "; 
              await operation.setContext((_, { headers = {} }) => ({
                headers: {
                  ...headers,
                  Authorization
                }
              }));
              const subscriber = {
                next: observer.next.bind(observer),
                error: observer.error.bind(observer),
                complete: observer.complete.bind(observer)
              };
              forward(operation).subscribe(subscriber);
            } catch (e) {
              observer.error(e);
            }
          });
        }
      }
      if (networkError) console.log(`[Network error]: ${networkError}`);
    }),
```


Then the token refresh would check if it's a client browser before actually doing it. I think the code would work something like this. I tried switching to Auth as a class because I wanted access to the auth0 object.
```
class Auth {
  auth0 = new auth0.WebAuth({ ...authSettings });

  login = () => this.auth0.authorize();

  parseHash = cb => this.auth0.parseHash(cb);

  logout = () => this.auth0.logout();

  silentAuth = async () => {
      if (typeof window !== "undefined") {
        console.log("in the browser, going to checksession");
         await this.auth0.checkSession({}, (err, authResult) => {
           //Do some sort of cookie storing here with authResult
         });
      }
  };
}
```

This code isn't 100% working at this point, but I think I'm on to something. I'll report back if I actually get this working with the pizzaql example. Thanks again!

**Comment by NatPagles** [comment]
This is the one of two things Im also trying to figure out. Getting token refreshing working and redirect to previous page after logging in. The new Auth0-SPA sdk makes this easy but it is only for the client side and wont work properly with Next.js

**Comment by xxczaki** [comment]
Closing this, as the rewritten version of PizzaQL is WIP - https://github.com/pizzaql/next
