### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [pizzaql/pizzaql#5]
Hello @xxczaki , I contribute to open source softwares by designing logos. For your the repo I have the idea of ​​an original logo in my mind. I would like to show you this if you have permission. what do you think?

**Comment by xxczaki** [comment]
@reallinfo You can show it :smile:

**Comment by reallinfo** [comment]
![pizzaql](https://user-images.githubusercontent.com/36298335/54853184-1938c380-4d00-11e9-98a3-f4a863880b8e.jpg)

**Comment by xxczaki** [comment]
@reallinfo Looks awesome 😮 The only thing that you could change is the name: use "PizzaQL" and not "Pizzaql" ;)

**Comment by reallinfo** [comment]
Oh okay. I made changes. Which variation do you want? 

![pizzaql](https://user-images.githubusercontent.com/36298335/54877549-f57d9680-4e41-11e9-8335-bd8a1aca9de4.jpg)

**Comment by xxczaki** [comment]
The first one (the bigger one)

**Comment by reallinfo** [comment]
I sent a pr. Please check it :)

**Comment by reallinfo** [comment]
I sent two pull requests, but don't mind the old one.

You can merged this. Thank you.

https://github.com/pizzaql/pizzaql/pull/7

**Comment by xxczaki** [comment]
Merged #7 :smile: Thanks!
