### ISSUE TITLE
Deploy monorepo with GitHub

### ISSUE THREAD

**Issue by rauchg** [pizzaql/pizzaql#9]
Amazing job!

Adding a `now.json` to the repo and [connecting with GitHub](https://zeit.co/github) will get every PR and commit deployed.

Furthermore, the master branch will be in sync with https://pizzaql.now.sh/ if you set `alias: ["pizzaql.now.sh."]` in your `now.json` :)

**Comment by xxczaki** [comment]
Thank you! 

Right now I'm not going to add the `now.json` file, as this project is still in early phase and some things might not work as expected. However, in the future I will deploy a working demo using `now` :smile:
